\documentclass[noraggedright]{turabian-researchpaper}

% Turabian Formatting
\usepackage{turabian-formatting}

% Chicago Bibliography Formatting
\usepackage[
  autocite = footnote,
  sorting=ynt,
  annotation]
  {biblatex-chicago}
   
\renewcommand{\bibfont}{\normalsize}
\addbibresource{Bibliography.bib}

% Language and Text Formatting
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{microtype}
\usepackage[greek, english]{babel}
  \babeltags{en = english}
  \babeltags{el = greek}
\usepackage{teubner}

% Packages recommended for Turabian
\usepackage{threeparttable}
\usepackage{ellipsis}
\usepackage{tocloft}
\usepackage{csquotes}

% Title Page
\title{This Great Flood of Words\thanks{Rep. 1: 344 d1}}
\subtitle{A Brief Phasal Analysis of the Dialogue
  between Socrates and Thrasymachus}
\author{Thomas Broadwater}
\course{GREK 8010: Readings and Research in Greek Literature}
\submissioninfo{}
\date{\today}

\usepackage{Sweave}
\begin{document}
\input{GreatFlood-concordance}





\maketitle

\input{Sections/Methodology.Rnw}
%\input{Sections/Sentences.Rnw}

\section{Sentences per Turn (Turn Density)}



The first portion of the code tallies the number of sentences per turn, hoping
to identify a correlation between turn ``density'' and the occurrence of phase
transitions. It counts the data in two ways. First, it gathers ``global''
calculations, i.e., the relevant information from the entire dialogue, and
second, it gathers speaker-by-speaker calculations. In order to construct a
high-level view of turn density, the script returns a table of calculations.
The mean represents the average number of sentences per turn, the median
represents the middle value when the data is organized numerically, and the mode
represents the middle value when organized. The standard deviation represents
the overall variation within the data. The table is printed below.

\begin{table}[htbp]
\begin{Schunk}
\begin{Soutput}
# A tibble: 6 × 5
  speaker      mean median  mode    sd
  <chr>       <dbl>  <dbl> <int> <dbl>
1 global       1.69    1       1 1.79 
2 cleitophon   1.33    1       1 0.577
3 glaucon      1.25    1       1 0.463
4 polemarchus  1.75    1.5     1 0.957
5 socrates     1.99    1       1 1.90 
6 thrasymacus  1.41    1       1 1.72 
\end{Soutput}
\end{Schunk}
\caption{Turn Density Data}
\label{tab:DensityData}
\end{table}

The table shows notably regular results. Each speaker's average sentence
density is close to the global, $P_{\bar{x}g} = 1.68$. Cleitophon and Socrates
deviate the most, $P_{\bar{x}c} = 1.33$ and $P_{\bar{x}s} = 1.99$, respectively, but
the variations are slight, making it difficult to tell what difference is
significant. The script performs a t-test comparing the global mean to each
speaker's to solve this problem. This test will return a figure called a
p-value for each speaker. For the purposes of this study, if a p-value is less
than 0.05, then the difference between the speaker's mean and the global mean
are significantly different. The results of the test are printed below.

\begin{table}[htbp]
\begin{Schunk}
\begin{Soutput}
[1] "cleitophon: 0.0755533142252797"
[1] "glaucon: 0.0953570075963998"
[1] "polemarchus: 0.0102844982210078"
[1] "socrates: 0.0514802153411887"
[1] "thrasymacus: 0.0581347985214711"
\end{Soutput}
\end{Schunk}
\caption{P-Values: Average Turn Density by Speaker}
\label{tab:DensityPval}
\end{table}

Interestingly, Only Polemarchus shows a statistically significant deviation from
the global mean. In Polemarchus' case, the small sample size may skew the data.
Polemarchus only has four turns in the entire dialogue. His third turn (P3) is
three sentences long, P2 is two sentences long, and P1 and P4 are both one
sentence long. As such, his result here provides little insight. 

Without any useful p-values to rely on, it becomes helpful to visualize the
data. Below is a histogram representing each turn in the order of occurrence.
The x-axis represents the index — a number identifying each turn in the data
set — and the y-axis represents the number of sentences in each turn. The blue
line represents the global mean density over time.

\begin{figure}[htbp]
\includegraphics{GreatFlood-Turn_Conseq}
\caption{Sentence Density by Speaker}
\label{graph:SentenceDensity}
\end{figure}

As reported by the initial data, the dialogue shows a consistent regularity in
sentence density. However, Socrates and Thrasymachus both show greater variation
than the others, especially in the early half of the text. 
This variation is measured by the standard deviations above. A similar t-test on
them reveals that both have a significantly high range of sentence densities:
$P_{\sigma s} = 0.02$ and $P_{\sigma t} = 0.01$ (both rounded), respectively. These
p-values imply that significantly denser turns than the average should be
considered when defining phases.

\begin{table}
\begin{Schunk}
\begin{Soutput}
[1] "cleitophon: 0.301818447656808"
[1] "glaucon: 0.339266024338994"
[1] "polemarchus: 0.187958111608137"
[1] "socrates: 0.0175810404193463"
[1] "thrasymacus: 0.0129304749109537"
\end{Soutput}
\end{Schunk}
\caption{P-Values: Standard Deviation of Turn Density by Speaker}
\label{tab:DSDPval}
\end{table}

\section{Words per Turn (Turn Length)}


The second part of the script follows the same pattern as the first, but now
tallies the number of words per turn, hoping to establish a correlation between
turn ``length'' and phase transitions.

Once again, the results are relatively consistent. Polemarchus, with his small
sample size, shows a statistically significant increase in words per turn,
giving him a noticeably high average turn length. However, when subject to a
t-test, the other interlocutors show p-values much higher than 0.05, indicating
that their averages are not statistically significant.

\begin{table}[htbp]
\begin{Schunk}
\begin{Soutput}
# A tibble: 6 × 5
  speaker      mean median  mode    sd
  <chr>       <dbl>  <dbl> <int> <dbl>
1 global      25.5      12     2 48.6 
2 cleitophon  20        17    NA 13.7 
3 glaucon      9.38      5     2  9.94
4 polemarchus 28.2      17    NA 32.3 
5 socrates    36.4      20    19 44.9 
6 thrasymacus 14.9       3     2 52.1 
\end{Soutput}
\end{Schunk}
\caption{Turn Length Data}
\label{tab:LengthData}
\end{table}

\begin{table}[htbp]
\begin{Schunk}
\begin{Soutput}
[1] "cleitophon: 0.076481767763397"
[1] "glaucon: 0.275646124468374"
[1] "polemarchus: 0.0326460198561527"
[1] "socrates: 0.111353038828907"
[1] "thrasymacus: 0.163542836119415"
\end{Soutput}
\end{Schunk}
\caption{P-Values: Average Turn Length by Speaker}
\label{tab:LenPval}
\end{table}

Socrates and Thrasymachus again show significantly higher standard deviations,
owing to a greater variety in turn length. Their p-values are
$P_{\sigma s} = 0.02$ and $P_{\sigma t} = 0.01$ (both rounded), respectively. 

\begin{table}[htbp]
\begin{Schunk}
\begin{Soutput}
[1] "cleitophon: 0.301818447656808"
[1] "glaucon: 0.339266024338994"
[1] "polemarchus: 0.187958111608137"
[1] "socrates: 0.0175810404193463"
[1] "thrasymacus: 0.0129304749109537"
\end{Soutput}
\end{Schunk}
\caption{P-Values: Standard Deviation of Turn Length by Speaker}
\label{tab:LSDPval}
\end{table}

The script once generates a histogram with a moving average, but now a
resemblance to the turn density chart becomes apparent. For comparison, both
figure \ref{graph:SentenceDensity} and the new figure \ref{graph:SentenceLength}
are reprinted below.

\begin{figure}[htbp]
\includegraphics{GreatFlood-Turn_Length}
\caption{Sentence Length by Speaker (Above) and Figure \ref{graph:SentenceDensity}. (Below)}
\label{graph:SentenceLength}
\end{figure}

\end{document}
